### ISSUE TITLE
Literally unplayable

### ISSUE THREAD

**Issue by JustinClough** [gochenaurd/Games_And_Simulations#1]
Just kidding, but actually since I've got octave I do get this error:
```
>> User_Run_File
warning: function name 'Gui_Test3' does not agree with function file name '/home/jlclough/Downloads/Games_And_Simulations/Minesweeper/User_Run_File.m'
error: 'gui_mainfcn' undefined near line 42 column 5
error: called from
    User_Run_File at line 42 column 5
```

I'm guessing that Matlab(tm) has a gui package with a `gui_mainfcn(...)` function that octave (or my copy of octave) does not. Still Cool!

To answer you github question: the _correct_ way depends on what you want to accomplish. Many people use it to publish and host tools, packages, and games like you're already doing. It also has version control and project management features. I wrote a short tutorial about the former [here if you want to check it out](https://github.com/OberaiGroup/getting_started/blob/master/tutorials_and_tools/git_crash_course.md).

**Comment by gochenaurd** [comment]
Justin, thanks for finding this. The issue is actually because I renamed some files after uploading them on GitHub to make them look better within the games folder, but I didn't change anything in the actual code. I'll fix it tomorrow and then you can check it out.

**Comment by gochenaurd** [comment]
Thanks for that link, I'll also read through that tomorrow.

**Comment by gochenaurd** [comment]
Justin, 
I've made a new run file that should work for the game if you'd still like to try it. The MATLAB GUI setup automatically generated a couple files based on the original name of the script. It was difficult to identify all these dependencies, so I created a new User_Run_File that simply calls the main script under the old name.

**Comment by JustinClough** [comment]
I finally got around to giving it another try. I can't run it on Octave but I'll try it again once I'm on a machine with real Matlab(tm). Cool project and good documentation!
